include(FindPackageHandleStandardArgs)
find_package(PkgConfig REQUIRED)

pkg_search_module(LIBINT2 libint2>=${LibINT2_FIND_VERSION})

find_library(LIBINT2_LIBRARIES NAMES int2
  PATH_SUFFIXES lib
  HINTS
  ENV_EBROOTLIBINT2
  ENV_LIBINT2ROOT
  ENV LIBINT2_ROOT
  ENV LIBINT_ROOT
  ENV LIBINT_PREFIX
  ENV LIBINT2_PREFIX
  ${_LIBINT2_LIBRARY_DIRS}
  DOC "libint2 libraries list"
  )

find_path(LIBINT2_INCLUDE_DIR NAMES NAMES libint2.h
  PATH_SUFFIXES inc include include/libint2 libint2
  HINTS
  ENV_EBROOTLIBINT2
  ENV_LIBINT2ROOT
  ENV LIBINT2_ROOT
  ENV LIBINT_ROOT
  ENV LIBINT_PREFIX
  ENV LIBINT2_PREFIX
  )

find_package_handle_standard_args(LibINT2 DEFAULT_MSG LIBINT2_LIBRARIES LIBINT2_INCLUDE_DIR)

if(LIBINT2_FOUND OR LIBINT2_LIBRARIES AND NOT TARGET libint2::libint2)
  add_library(libint2::libint2 INTERFACE IMPORTED)
  set_target_properties(libint2::libint2 PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${LIBINT2_INCLUDE_DIR}"
    INTERFACE_LINK_DIRECTORIES "${_LIBINT2_LIBRARY_DIRS}"
    INTERFACE_LINK_LIBRARIES "${LIBINT2_LIBRARIES}")
endif()
